### ISSUE TITLE
Missmatch of VL data types in deffered version

### ISSUE THREAD

**Issue by seltzdesign** [michael-burk/SuperPhysical#3]
Just trying out the deferred version and opening the deffered help patch I get some red VL nodes and wires, due to a missmatch of data types.

For example in the Material Visualizer (SuperPhysical).v4p the SplitLightSetup node outputs [GlobalSettings, Object], but LightSetup expects [GlobalSettings]. Same with [LightSetup].

Hope those last little things get ironed out. I'll take a look at it with VL-guru tonfilm today and see if we can fix it.

https://www.dropbox.com/s/3i6q2vf2k3zizgl/superphysical_VL.PNG?dl=0

**Comment by michael-burk** [comment]
hi,
yeah I've had issues like this before. seems like sometimes the VL modules
are referencing other / older versions that are around somewhere.
keep in mind that this branch is a WIP, so make sure to pull the latest
version.
would be cool if you guys have any insights.
best,
michael

2018-05-29 11:16 GMT+02:00 Armin Seltz <notifications@github.com>:

**Comment by seltzdesign** [comment]
Maybe it has to do with this. Seems like it cant find 2 dependencies:

https://www.dropbox.com/s/2elfk3j7wr57pg0/forward_dependencies.PNG?dl=0

I have beta36 and latest dx 11.3. Superphysical 2.01 is running fine.

edit: the file it is looking for is there, so either the path it is using is not correct or something else entirely.

**Comment by michael-burk** [comment]
hmm..sorry hard to say.
I have it running here on different machines and it's always working.
what you can try is to delete the nodes that have red outputs, create them
again and see if that works out.

2018-05-29 11:57 GMT+02:00 Armin Seltz <notifications@github.com>:

**Comment by seltzdesign** [comment]
Right, found the error. Had to remove Superphysical 2.01 from packs first, because the nodes are named the same and it had taken the one from the other pack. Working fine now and still getting 70fps with 3000 tea pots. Nice! 

Only thing I cant work out, is how you specify which material to give to each instance. The SelectedMaterial output of Material Visualizer is NIL. But I guess I'll have a look around. Also Roughness and Metallicness needs to be setable at a per instance basis.

**Comment by michael-burk** [comment]
Hey. Good to hear that it works in principle.
The material assignment is not well documented (at all) yet, sorry and
still a bit experimental and confusing. There is the playful feature at the
moment that you can press m + klick in the material viewer and then press m
+ klick in the scene preview to assign a material with a "drag & drop" like
style. In the end there is just a spread which defines the material per
instance. So at the moment you can only assign a material per instance.
There is no possibillity yet to assign a roughness for each instance at the
moment.

2018-05-29 14:20 GMT+02:00 Armin Seltz <notifications@github.com>:
